import pytest
import time
import pandas as pd
from pages.MainPage import MainPage
from pages.ProductPage import ProductPage
from pages.ShoppingCartPage import ShoppingCartPage
from pages.SummaryPage import SummaryPage
from pages.ExtraoptionsPage import ExtraoptionsPage
from pages.CheckoutDeliveryPage import CheckoutDeliveryPage
from pages.CreateAccountPage import CreateAccountPage
import allure

@pytest.mark.usefixtures('setup')
class Test_Sale:
    xl = pd.read_excel('FILEPATH\\Dane.xlsx', sheet_name="Arkusz1")
    baseURL = xl.at[0, 'Wartosc']
    productURL = xl.at[16, 'Wartosc']
    email = xl.at[1, 'Wartosc']
    password = xl.at[3, 'Wartosc']
    name = xl.at[5, 'Wartosc']
    lastname = xl.at[6, 'Wartosc']
    phone = xl.at[8, 'Wartosc']
    street = xl.at[12, 'Wartosc']
    postcode = xl.at[13, 'Wartosc']
    city = xl.at[14, 'Wartosc']
    comment = xl.at[15, 'Wartosc']
    search_keyword = xl.at[10, 'Wartosc']
    
    @allure.title('Test sprzedaży Kurier DHL + PayU dla niezalogowanego użytkownika')
    def test_sale_1(self):
        # pytest.skip()
        self.driver.get(self.productURL)           # otwiera stronę, która jest wskazana w zmiennej productURL
        self.mp = MainPage(self.driver)         # (mp - main page) wyznacza zmienną self.mp na bazie MainPage
        self.pp  = ProductPage(self.driver)     # (pp - product page) wyznacza zmienną self.pp na bazie ProductPage
        self.scp = ShoppingCartPage(self.driver)     # (scp - Shopping Cart page) wyznacza zmienną self.cp na bazie ShoppingCartPage
        self.sump = SummaryPage(self.driver)        # (sump - Summary Page) wyznacza zmienną self.cp na bazie SummaryPage
        self.ex = ExtraoptionsPage(self.driver)       # (ex - Extraoptions) wyznacza zmienną self.ex na bazie ExtraoptionsPage
        self.cdp = CheckoutDeliveryPage(self.driver)    # (cdp - Checkout Delivery Page) wyznacza zmienną self.cap na bazie CCheckoutDeliveryPage
        self.cap = CreateAccountPage(self.driver)   # (cap - create account page) wyznacza zmienną self.cap na bazie CreateAccountPage
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCart()
        self.ex.clickGoToCart()
        self.scp.clickGoToOrderButton()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.clickProceedToSummaryButton()
        time.sleep(3)
        self.sump.clickCheckbox1()
        self.sump.clickCheckbox2()
        self.sump.clickOrderAndPayButton()
        time.sleep(3)
        self.sump.AssertPayUTitle()

    @allure.title('Test sprzedaży Kurier DHL + Blik dla niezalogowanego użytkownika')
    def test_sale_2(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCart()
        self.ex.clickGoToCart()
        self.scp.clickGoToOrderButton()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.clickProceedToSummaryButton()
        time.sleep(3)
        self.sump.selectBlik()
        time.sleep(1)
        self.sump.clickCheckbox1()
        self.sump.clickCheckbox2()
        self.sump.clickOrderAndPayButton()
        time.sleep(3)
        self.sump.AssertPayUTitle()


    @allure.title('Test sprzedaży Kurier DHL + Apple Pay dla niezalogowanego użytkownika')
    def test_sale_3(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCart()
        self.ex.clickGoToCart()
        self.scp.clickGoToOrderButton()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.clickProceedToSummaryButton()
        time.sleep(3)
        self.sump.selectApplePay()
        time.sleep(1)
        self.sump.clickCheckbox1()
        self.sump.clickCheckbox2()
        self.sump.clickOrderAndPayButton()
        time.sleep(3)
        self.sump.AssertPayUTitle()

    @allure.title('Test sprzedaży Kurier DHL + Raty PayU dla niezalogowanego użytkownika')
    def test_sale_4(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCart()
        self.ex.clickGoToCart()
        self.scp.clickGoToOrderButton()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.clickProceedToSummaryButton()
        time.sleep(3)
        self.sump.selectRatyPayU()
        time.sleep(1)
        self.sump.clickCheckbox1()
        self.sump.clickCheckbox2()
        self.sump.clickOrderAndPayButton()
        time.sleep(3)
        self.sump.AssertPayUTitle()

    @allure.title('Test sprzedaży Kurier DHL + Raty CA dla niezalogowanego użytkownika')
    def test_sale_5(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCart()
        self.ex.clickGoToCart()
        self.scp.clickGoToOrderButton()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.clickProceedToSummaryButton()
        time.sleep(3)
        self.sump.selectRatyCA()
        time.sleep(1)
        self.sump.clickCheckbox1()
        self.sump.clickCheckbox2()
        self.sump.clickOrderAndPayButton()
        time.sleep(3)
        self.sump.AssertRatyCATitle()

    @allure.title('Test sprzedaży Kurier DHL + Twisto dla niezalogowanego użytkownika')
    def test_sale_6(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCart()
        self.ex.clickGoToCart()
        self.scp.clickGoToOrderButton()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.clickProceedToSummaryButton()
        time.sleep(3)
        self.sump.selectTwisto()
        time.sleep(1)
        self.sump.clickCheckbox1()
        self.sump.clickCheckbox2()
        self.sump.clickOrderAndPayButton()
        time.sleep(3)
        self.sump.AssertPayUTitle()

    @allure.title('Test sprzedaży Kurier DHL + Przelew tradycyjny dla niezalogowanego użytkownika')
    def test_sale_7(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCart()
        self.ex.clickGoToCart()
        self.scp.clickGoToOrderButton()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.clickProceedToSummaryButton()
        time.sleep(3)
        self.sump.selectBankTransfer()
        time.sleep(1)
        self.sump.clickCheckbox1()
        self.sump.clickCheckbox2()
        self.sump.clickOrderAndPayButton()
        time.sleep(3)
        self.sump.AssertSuccessPage()

    @allure.title('Test sprzedaży Kurier DHL + PayPal dla niezalogowanego użytkownika')
    def test_sale_8(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCart()
        self.ex.clickGoToCart()
        self.scp.clickGoToOrderButton()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.clickProceedToSummaryButton()
        time.sleep(3)
        self.sump.selectPayPal()
        time.sleep(1)
        self.sump.clickCheckbox1()
        self.sump.clickCheckbox2()
        self.sump.clickOrderAndPayButton()
        time.sleep(3)
        self.sump.AssertPayPalTitle()
